dist: trusty
sudo: false
language: php

php:
- 7.1
- 7.2
- 7.3
- nightly

cache:
  directories:
  - $HOME/.composer/cache

jobs:
  allow_failures:
  - php: nightly

  exclude:
  - php: 7.2

  include:
  - stage: Test
    php: 7.2

  - stage: Lint
    install: travis_retry composer require --dev --prefer-dist phpstan/phpstan:^0.10
    script: vendor/bin/phpstan analyse -l max src tests
